MODULE = limera1n

SRCS = limera1n.c

include ../../extra.mk
include ../../buildsys.mk
include ../../buildsys.module.mk

CPPFLAGS	+= -I../../include -I../../include/libusb-1.0 -I../../include/xpwntool
LIBS		+= -L../../libsn0wcore -lsn0wcore ${LDFLAGS_RPATH}